<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run ()
    {
        $cities = [
            array (1, 1, 'القاهره', 'Cairo'),
            array (2, 2, 'الجيزة', 'Giza'),
            array (3, 2, 'السادس من أكتوبر', 'Sixth of October'),
            array (4, 2, 'الشيخ زايد\n', 'Cheikh Zayed'),
            array (5, 2, 'الحوامدية', 'Hawamdiyah'),
            array (6, 2, 'البدرشين', 'Al Badrasheen'),
            array (7, 2, 'الصف', 'Saf'),
            array (8, 2, 'أطفيح', 'Atfih'),
            array (9, 2, 'العياط', 'Al Ayat'),
            array (10, 2, 'الباويطي', 'Al-Bawaiti'),
            array (11, 2, 'منشأة القناطر', 'ManshiyetAl Qanater'),
            array (12, 2, 'أوسيم', 'Oaseem'),
            array (13, 2, 'كرداسة', 'Kerdasa'),
            array (14, 2, 'أبو النمرس', 'Abu Nomros'),
            array (15, 2, 'كفر غطاطي', 'Kafr Ghati'),
            array (16, 2, 'منشأة البكاري', 'Manshiyet Al Bakari'),
            array (17, 3, 'الأسكندرية', 'Alexandria'),
            array (18, 3, 'برج العرب', 'Burj Al Arab'),
            array (19, 3, 'برج العرب الجديدة', 'New Burj Al Arab'),
            array (20, 12, 'بنها', 'Banha'),
            array (21, 12, 'قليوب', 'Qalyub'),
            array (22, 12, 'شبرا الخيمة', 'Shubra Al Khaimah'),
            array (23, 12, 'القناطر الخيرية', 'Al Qanater Charity'),
            array (24, 12, 'الخانكة', 'Khanka'),
            array (25, 12, 'كفر شكر', 'Kafr Shukr'),
            array (26, 12, 'طوخ', 'Tukh'),
            array (27, 12, 'قها', 'Qaha'),
            array (28, 12, 'العبور', 'Obour'),
            array (29, 12, 'الخصوص', 'Khosous'),
            array (30, 12, 'شبين القناطر', 'Shibin Al Qanater'),
            array (31, 6, 'دمنهور', 'Damanhour'),
            array (32, 6, 'كفر الدوار', 'Kafr El Dawar'),
            array (33, 6, 'رشيد', 'Rashid'),
            array (34, 6, 'إدكو', 'Edco'),
            array (35, 6, 'أبو المطامير', 'Abu al-Matamir'),
            array (36, 6, 'أبو حمص', 'Abu Homs'),
            array (37, 6, 'الدلنجات', 'Delengat'),
            array (38, 6, 'المحمودية', 'Mahmoudiyah'),
            array (39, 6, 'الرحمانية', 'Rahmaniyah'),
            array (40, 6, 'إيتاي البارود', 'Itai Baroud'),
            array (41, 6, 'حوش عيسى', 'Housh Eissa'),
            array (42, 6, 'شبراخيت', 'Shubrakhit'),
            array (43, 6, 'كوم حمادة', 'Kom Hamada'),
            array (44, 6, 'بدر', 'Badr'),
            array (45, 6, 'وادي النطرون', 'Wadi Natrun'),
            array (46, 6, 'النوبارية الجديدة', 'New Nubaria'),
            array (47, 23, 'مرسى مطروح', 'Marsa Matrouh'),
            array (48, 23, 'الحمام', 'El Hamam'),
            array (49, 23, 'العلمين', 'Alamein'),
            array (50, 23, 'الضبعة', 'Dabaa'),
            array (51, 23, 'النجيلة', 'Al-Nagila'),
            array (52, 23, 'سيدي براني', 'Sidi Brani'),
            array (53, 23, 'السلوم', 'Salloum'),
            array (54, 23, 'سيوة', 'Siwa'),
            array (55, 19, 'دمياط', 'Damietta'),
            array (56, 19, 'دمياط الجديدة', 'New Damietta'),
            array (57, 19, 'رأس البر', 'Ras El Bar'),
            array (58, 19, 'فارسكور', 'Faraskour'),
            array (59, 19, 'الزرقا', 'Zarqa'),
            array (60, 19, 'السرو', 'alsaru'),
            array (61, 19, 'الروضة', 'alruwda'),
            array (62, 19, 'كفر البطيخ', 'Kafr El-Batikh'),
            array (63, 19, 'عزبة البرج', 'Azbet Al Burg'),
            array (64, 19, 'ميت أبو غالب', 'Meet Abou Ghalib'),
            array (65, 19, 'كفر سعد', 'Kafr Saad'),
            array (66, 4, 'المنصورة', 'Mansoura'),
            array (67, 4, 'طلخا', 'Talkha'),
            array (68, 4, 'ميت غمر', 'Mitt Ghamr'),
            array (69, 4, 'دكرنس', 'Dekernes'),
            array (70, 4, 'أجا', 'Aga'),
            array (71, 4, 'منية النصر', 'Menia El Nasr'),
            array (72, 4, 'السنبلاوين', 'Sinbillawin'),
            array (73, 4, 'الكردي', 'El Kurdi'),
            array (74, 4, 'بني عبيد', 'Bani Ubaid'),
            array (75, 4, 'المنزلة', 'Al Manzala'),
            array (76, 4, 'تمي الأمديد', 'tami al\'amdid'),
            array (77, 4, 'الجمالية', 'aljamalia'),
            array (78, 4, 'شربين', 'Sherbin'),
            array (79, 4, 'المطرية', 'Mataria'),
            array (80, 4, 'بلقاس', 'Belqas'),
            array (81, 4, 'ميت سلسيل', 'Meet Salsil'),
            array (82, 4, 'جمصة', 'Gamasa'),
            array (83, 4, 'محلة دمنة', 'Mahalat Damana'),
            array (84, 4, 'نبروه', 'Nabroh'),
            array (85, 22, 'كفر الشيخ', 'Kafr El Sheikh'),
            array (86, 22, 'دسوق', 'Desouq'),
            array (87, 22, 'فوه', 'Fooh'),
            array (88, 22, 'مطوبس', 'Metobas'),
            array (89, 22, 'برج البرلس', 'Burg Al Burullus'),
            array (90, 22, 'بلطيم', 'Baltim'),
            array (91, 22, 'مصيف بلطيم', 'Masief Baltim'),
            array (92, 22, 'الحامول', 'Hamol'),
            array (93, 22, 'بيلا', 'Bella'),
            array (94, 22, 'الرياض', 'Riyadh'),
            array (95, 22, 'سيدي سالم', 'Sidi Salm'),
            array (96, 22, 'قلين', 'Qellen'),
            array (97, 22, 'سيدي غازي', 'Sidi Ghazi'),
            array (98, 8, 'طنطا', 'Tanta'),
            array (99, 8, 'المحلة الكبرى', 'Al Mahalla Al Kobra'),
            array (100, 8, 'كفر الزيات', 'Kafr El Zayat'),
            array (101, 8, 'زفتى', 'Zefta'),
            array (102, 8, 'السنطة', 'El Santa'),
            array (103, 8, 'قطور', 'Qutour'),
            array (104, 8, 'بسيون', 'Basion'),
            array (105, 8, 'سمنود', 'Samannoud'),
            array (106, 10, 'شبين الكوم', 'Shbeen El Koom'),
            array (107, 10, 'مدينة السادات', 'Sadat City'),
            array (108, 10, 'منوف', 'Menouf'),
            array (109, 10, 'سرس الليان', 'Sars El-Layan'),
            array (110, 10, 'أشمون', 'Ashmon'),
            array (111, 10, 'الباجور', 'Al Bagor'),
            array (112, 10, 'قويسنا', 'Quesna'),
            array (113, 10, 'بركة السبع', 'Berkat El Saba'),
            array (114, 10, 'تلا', 'Tala'),
            array (115, 10, 'الشهداء', 'Al Shohada'),
            array (116, 20, 'الزقازيق', 'Zagazig'),
            array (117, 20, 'العاشر من رمضان', 'Al Ashr Men Ramadan'),
            array (118, 20, 'منيا القمح', 'Minya Al Qamh'),
            array (119, 20, 'بلبيس', 'Belbeis'),
            array (120, 20, 'مشتول السوق', 'Mashtoul El Souq'),
            array (121, 20, 'القنايات', 'Qenaiat'),
            array (122, 20, 'أبو حماد', 'Abu Hammad'),
            array (123, 20, 'القرين', 'El Qurain'),
            array (124, 20, 'ههيا', 'Hehia'),
            array (125, 20, 'أبو كبير', 'Abu Kabir'),
            array (126, 20, 'فاقوس', 'Faccus'),
            array (127, 20, 'الصالحية الجديدة', 'El Salihia El Gedida'),
            array (128, 20, 'الإبراهيمية', 'Al Ibrahimiyah'),
            array (129, 20, 'ديرب نجم', 'Deirb Negm'),
            array (130, 20, 'كفر صقر', 'Kafr Saqr'),
            array (131, 20, 'أولاد صقر', 'Awlad Saqr'),
            array (132, 20, 'الحسينية', 'Husseiniya'),
            array (133, 20, 'صان الحجر القبلية', 'san alhajar alqablia'),
            array (134, 20, 'منشأة أبو عمر', 'Manshayat Abu Omar'),
            array (135, 18, 'بورسعيد', 'PorSaid'),
            array (136, 18, 'بورفؤاد', 'PorFouad'),
            array (137, 9, 'الإسماعيلية', 'Ismailia'),
            array (138, 9, 'فايد', 'Fayed'),
            array (139, 9, 'القنطرة شرق', 'Qantara Sharq'),
            array (140, 9, 'القنطرة غرب', 'Qantara Gharb'),
            array (141, 9, 'التل الكبير', 'El Tal El Kabier'),
            array (142, 9, 'أبو صوير', 'Abu Sawir'),
            array (143, 9, 'القصاصين الجديدة', 'Kasasien El Gedida'),
            array (144, 14, 'السويس', 'Suez'),
            array (145, 26, 'العريش', 'Arish'),
            array (146, 26, 'الشيخ زويد', 'Sheikh Zowaid'),
            array (147, 26, 'نخل', 'Nakhl'),
            array (148, 26, 'رفح', 'Rafah'),
            array (149, 26, 'بئر العبد', 'Bir al-Abed'),
            array (150, 26, 'الحسنة', 'Al Hasana'),
            array (151, 21, 'الطور', 'Al Toor'),
            array (152, 21, 'شرم الشيخ', 'Sharm El-Shaikh'),
            array (153, 21, 'دهب', 'Dahab'),
            array (154, 21, 'نويبع', 'Nuweiba'),
            array (155, 21, 'طابا', 'Taba'),
            array (156, 21, 'سانت كاترين', 'Saint Catherine'),
            array (157, 21, 'أبو رديس', 'Abu Redis'),
            array (158, 21, 'أبو زنيمة', 'Abu Zenaima'),
            array (159, 21, 'رأس سدر', 'Ras Sidr'),
            array (160, 17, 'بني سويف', 'Bani Sweif'),
            array (161, 17, 'بني سويف الجديدة', 'Beni Suef El Gedida'),
            array (162, 17, 'الواسطى', 'Al Wasta'),
            array (163, 17, 'ناصر', 'Naser'),
            array (164, 17, 'إهناسيا', 'Ehnasia'),
            array (165, 17, 'ببا', 'beba'),
            array (166, 17, 'الفشن', 'Fashn'),
            array (167, 17, 'سمسطا', 'Somasta'),
            array (168, 7, 'الفيوم', 'Fayoum'),
            array (169, 7, 'الفيوم الجديدة', 'Fayoum El Gedida'),
            array (170, 7, 'طامية', 'Tamiya'),
            array (171, 7, 'سنورس', 'Snores'),
            array (172, 7, 'إطسا', 'Etsa'),
            array (173, 7, 'إبشواي', 'Epschway'),
            array (174, 7, 'يوسف الصديق', 'Yusuf El Sediaq'),
            array (175, 11, 'المنيا', 'Minya'),
            array (176, 11, 'المنيا الجديدة', 'Minya El Gedida'),
            array (177, 11, 'العدوة', 'El Adwa'),
            array (178, 11, 'مغاغة', 'Magagha'),
            array (179, 11, 'بني مزار', 'Bani Mazar'),
            array (180, 11, 'مطاي', 'Mattay'),
            array (181, 11, 'سمالوط', 'Samalut'),
            array (182, 11, 'المدينة الفكرية', 'Madinat El Fekria'),
            array (183, 11, 'ملوي', 'Meloy'),
            array (184, 11, 'دير مواس', 'Deir Mawas'),
            array (185, 16, 'أسيوط', 'Assiut'),
            array (186, 16, 'أسيوط الجديدة', 'Assiut El Gedida'),
            array (187, 16, 'ديروط', 'Dayrout'),
            array (188, 16, 'منفلوط', 'Manfalut'),
            array (189, 16, 'القوصية', 'Qusiya'),
            array (190, 16, 'أبنوب', 'Abnoub'),
            array (191, 16, 'أبو تيج', 'Abu Tig'),
            array (192, 16, 'الغنايم', 'El Ghanaim'),
            array (193, 16, 'ساحل سليم', 'Sahel Selim'),
            array (194, 16, 'البداري', 'El Badari'),
            array (195, 16, 'صدفا', 'Sidfa'),
            array (196, 13, 'الخارجة', 'El Kharga'),
            array (197, 13, 'باريس', 'Paris'),
            array (198, 13, 'موط', 'Mout'),
            array (199, 13, 'الفرافرة', 'Farafra'),
            array (200, 13, 'بلاط', 'Balat'),
            array (201, 5, 'الغردقة', 'Hurghada'),
            array (202, 5, 'رأس غارب', 'Ras Ghareb'),
            array (203, 5, 'سفاجا', 'Safaga'),
            array (204, 5, 'القصير', 'El Qusiar'),
            array (205, 5, 'مرسى علم', 'Marsa Alam'),
            array (206, 5, 'الشلاتين', 'Shalatin'),
            array (207, 5, 'حلايب', 'Halaib'),
            array (208, 27, 'سوهاج', 'Sohag'),
            array (209, 27, 'سوهاج الجديدة', 'Sohag El Gedida'),
            array (210, 27, 'أخميم', 'Akhmeem'),
            array (211, 27, 'أخميم الجديدة', 'Akhmim El Gedida'),
            array (212, 27, 'البلينا', 'Albalina'),
            array (213, 27, 'المراغة', 'El Maragha'),
            array (214, 27, 'المنشأة', 'almunsha\'a'),
            array (215, 27, 'دار السلام', 'Dar AISalaam'),
            array (216, 27, 'جرجا', 'Gerga'),
            array (217, 27, 'جهينة الغربية', 'Jahina Al Gharbia'),
            array (218, 27, 'ساقلته', 'Saqilatuh'),
            array (219, 27, 'طما', 'Tama'),
            array (220, 27, 'طهطا', 'Tahta'),
            array (221, 25, 'قنا', 'Qena'),
            array (222, 25, 'قنا الجديدة', 'New Qena'),
            array (223, 25, 'أبو تشت', 'Abu Tesht'),
            array (224, 25, 'نجع حمادي', 'Nag Hammadi'),
            array (225, 25, 'دشنا', 'Deshna'),
            array (226, 25, 'الوقف', 'Alwaqf'),
            array (227, 25, 'قفط', 'Qaft'),
            array (228, 25, 'نقادة', 'Naqada'),
            array (229, 25, 'فرشوط', 'Farshout'),
            array (230, 25, 'قوص', 'Quos'),
            array (231, 24, 'الأقصر', 'Luxor'),
            array (232, 24, 'الأقصر الجديدة', 'New Luxor'),
            array (233, 24, 'إسنا', 'Esna'),
            array (234, 24, 'طيبة الجديدة', 'New Tiba'),
            array (235, 24, 'الزينية', 'Al ziynia'),
            array (236, 24, 'البياضية', 'Al Bayadieh'),
            array (237, 24, 'القرنة', 'Al Qarna'),
            array (238, 24, 'أرمنت', 'Armant'),
            array (239, 24, 'الطود', 'Al Tud'),
            array (240, 15, 'أسوان', 'Aswan'),
            array (241, 15, 'أسوان الجديدة', 'Aswan El Gedida'),
            array (242, 15, 'دراو', 'Drau'),
            array (243, 15, 'كوم أمبو', 'Kom Ombo'),
            array (244, 15, 'نصر النوبة', 'Nasr Al Nuba'),
            array (245, 15, 'كلابشة', 'Kalabsha'),
            array (246, 15, 'إدفو', 'Edfu'),
            array (247, 15, 'الرديسية', 'Al-Radisiyah'),
            array (248, 15, 'البصيلية', 'Al Basilia'),
            array (249, 15, 'السباعية', 'Al Sibaeia'),
            array (250, 15, 'ابوسمبل السياحية', 'Abo Simbl Al Siyahia')
        ];

        foreach ($cities as $city) {
            \App\Models\City::create([
                'governorate_id' => $city[1],
                'name' => $city[2],
            ]);
        }
    }
}
